# MIT License - Copyright (c) 2020 Stefan Arentz <stefan@devbots.xyz>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: 'Carthage Bootstrap'
description: 'Bootstrap and cache Carthage dependencies.'

inputs:
  github-token:
    description: "GitHub Access Token uses for fetching dependencies."
    required: true

  platform:
    description: "The platforms to build for. One of 'all', 'macOS', 'iOS', 'watchOS', 'tvOS', or comma-separated values of the formers except for 'all'."
    required: false

  no-use-binaries:
    description: "Do not use downloaded binaries when possible."
    required: false

  use-xcframeworks:
    description: "Create xcframework bundles instead of one framework per platform (requires Xcode 12+)."
    required: false

  verbose:
    description: "Print xcodebuild output inline."
    required: false
    default: false

runs:
  using: 'node16'
  main: 'dist/index.js'
